language: node_js
sudo: required
dist: trusty
env: 
  - NODE_ENV = test
  - TEST_ENV = xvfb-run polymer test test/app
  - TEST_ENV = mocha test/api/**/*.test.js
services: 
  - mongodb
  - redis-server
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli
script: " $TEST_ENV"