language: node_js
sudo: required
dist: trusty
services:
  - mongodb
  - redis-server
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower web-component-tester
script:
  - mocha test/api/**/*.test.js
